### ISSUE TITLE
Symbol issues with PPC64 ABIv1

### ISSUE THREAD

**Issue by ruscur** [joe-lawrence/klp-convert-tree#9]
PPC64 has two ABIs, v1 and v2.  In practical terms, v1 gets used by BE and v2 gets used by LE (v2 does define BE support but no compiler implements it).

Building for PPC64 ABIv1 does something weird with symbols that I don't entirely understand, which prefixes them with `.`.  This leads to duplicate entries in `symbols.klp` where symbols have both `.`-prefixed and non-prefixed entries.

Attempting to look up a `.`-prefixed symbol fails when linking, i.e.

```
KLP_MODULE_RELOC(vmlinux) vmlinux_relocs[] = {
	KLP_SYMPOS(saved_command_line, 0)
};
```

can't find `._mcount`, hack around that and it can't find `._printk`, etc.

I'm not sure what the proper solution is, but hacking

```
	if (strncmp(sym->name, ".", 1) == 0)
		return true;
```

in `skip_symbol()` successfully builds.

**Comment by joe-lawrence** [comment]
Hi @ruscur , thanks for the report. I'm currently on PTO so won't get a chance to try it for a while.  BTW, is livepatch on ppc64be supported upstream, I've never tried it.

**Comment by ruscur** [comment]
Oh, it's not.  I just assumed it was without checking.  PPC64BE doesn't have `-mprofile-kernel` which is a prerequisite for livepatch.

Closing this issue then.  Enjoy your PTO :)
